root_vpc_cidr_block  = "10.0.0.0/16"
root_environment     = "staging"
root_aws_region      = "us-east-1"
root_aws_zone1       = "us-east-1a"
root_aws_zone2       = "us-east-1b"
root_aws_eks_name    = "staging-cluster"
root_aws_eks_version = "1.33"